// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoLghlYdeObietKOuJAsvARcDAHCHYdq4',
    appId: '1:997495243061:web:a1f6773cb8bc5c0d698c7c',
    messagingSenderId: '997495243061',
    projectId: 'hunarmandkashmir',
    authDomain: 'hunarmandkashmir.firebaseapp.com',
    storageBucket: 'hunarmandkashmir.firebasestorage.app',
    measurementId: 'G-5C968QB5ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCArnId98lz0O9ggQdb1qNuaygVfYnAu9c',
    appId: '1:997495243061:android:5d7a043c43baa967698c7c',
    messagingSenderId: '997495243061',
    projectId: 'hunarmandkashmir',
    storageBucket: 'hunarmandkashmir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBURY0lugaB8gWNLGroHSzuvHL-xafWktE',
    appId: '1:997495243061:ios:6600baf24c1d5cc3698c7c',
    messagingSenderId: '997495243061',
    projectId: 'hunarmandkashmir',
    storageBucket: 'hunarmandkashmir.firebasestorage.app',
    iosBundleId: 'com.example.hunarmandKashmir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBURY0lugaB8gWNLGroHSzuvHL-xafWktE',
    appId: '1:997495243061:ios:6600baf24c1d5cc3698c7c',
    messagingSenderId: '997495243061',
    projectId: 'hunarmandkashmir',
    storageBucket: 'hunarmandkashmir.firebasestorage.app',
    iosBundleId: 'com.example.hunarmandKashmir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoLghlYdeObietKOuJAsvARcDAHCHYdq4',
    appId: '1:997495243061:web:a33d3c6f6d61a85b698c7c',
    messagingSenderId: '997495243061',
    projectId: 'hunarmandkashmir',
    authDomain: 'hunarmandkashmir.firebaseapp.com',
    storageBucket: 'hunarmandkashmir.firebasestorage.app',
    measurementId: 'G-GWT995YSPE',
  );
}
